version: 0.2

phases:
    install:
        commands:
            - echo Installation started...
            - npm install typescript -g
    pre_build:
        commands:
            - echo pre-build
            - npm install  
            - echo building npm
            - echo Stage 2

    build:
        commands:
            - echo deployment started..$BUILD_OUTPUT_BUCKET
            - node --version
            - npm --version
            - npm run cicd_deploy-dev
            - sam package --output-template-file package.yml --s3-bucket $BUILD_OUTPUT_BUCKET
            
    post_build:
        commands:
            - echo deployment complete..
artifacts:
    files:
        - package.yml
        - 'dist/**/*'
