version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-skt160kydc9"
s3_prefix = "sample"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\" ProductLine=\"data-channels\""

