export const usersFileHeaderRow = {
  index: 1,
  raw: [
    "integration_id",
    "family_name",
    "middle_name",
    "given_name",
    "email",
    "secondary_email",
    "student_id",
    "user_id",
    "gender",
    "birth_dt",
    "b_phone",
    "m_phone",
    "available_ind",
    "assign_student_role",
    "allow_login",
    "home_city",
    "home_state",
    "home_zip",
    "home_county",
    "user_timezone",
  ],
  data: {
    integration_id: "integration_id",
    family_name: "family_name",
    middle_name: "middle_name",
    given_name: "given_name",
    email: "email",
    secondary_email: "secondary_email",
    student_id: "student_id",
    user_id: "user_id",
    gender: "gender",
    birth_dt: "birth_dt",
    b_phone: "b_phone",
    m_phone: "m_phone",
    available_ind: "available_ind",
    assign_student_role: "assign_student_role",
    allow_login: "allow_login",
    home_city: "home_city",
    home_state: "home_state",
    home_zip: "home_zip",
    home_county: "home_county",
    user_timezone: "user_timezone",
  },
  json: [
    "integration_id",
    "family_name",
    "middle_name",
    "given_name",
    "email",
    "secondary_email",
    "student_id",
    "user_id",
    "gender",
    "birth_dt",
    "b_phone",
    "m_phone",
    "available_ind",
    "assign_student_role",
    "allow_login",
    "home_city",
    "home_state",
    "home_zip",
    "home_county",
    "user_timezone",
  ],
  name: "users",
};

export const usersFileWithPIIDataRow = {
  index: 2,
  raw: [
    "Yolanda.Gold",
    "goldnew",
    "testnew",
    "yolandanew",
    "testusernew@gmail.com",
    "testusernew@gmail.com",
    "C0018992",
    "ygold_test",
    "Female",
    "2001-02-21",
    "17035551213",
    "17035551213",
    "1",
    "1",
    "1",
    "Honolulu",
    "Hawaii",
    "96815",
    "Honolulu",
    "America/Adak",
  ],
  data: {
    integration_id: "Yolanda.Gold",
    family_name: "goldnew",
    middle_name: "testnew",
    given_name: "yolandanew",
    email: "testusernew@gmail.com",
    secondary_email: "testusernew@gmail.com",
    student_id: "C0018992",
    user_id: "ygold_test",
    gender: "Female",
    birth_dt: "2001-02-21",
    b_phone: "17035551213",
    m_phone: "17035551213",
    available_ind: "1",
    assign_student_role: "1",
    allow_login: "1",
    home_city: "Honolulu",
    home_state: "Hawaii",
    home_zip: "96815",
    home_county: "Honolulu",
    user_timezone: "America/Adak",
  },
  json: [
    "Yolanda.Gold",
    "goldnew",
    "testnew",
    "yolandanew",
    "testusernew@gmail.com",
    "testusernew@gmail.com",
    "C0018992",
    "ygold_test",
    "Female",
    "2001-02-21",
    "17035551213",
    "17035551213",
    "1",
    "1",
    "1",
    "Honolulu",
    "Hawaii",
    "96815",
    "Honolulu",
    "America/Adak",
  ],
  name: "users",
};

export const usersFileWithoutEmailWithSpeacialCharacters = {
  index: 3,
  raw: [
    "Egon.Adam",
    "adam@#,%^&*-_;|test",
    "test2",
    "egon",
    "",
    "testuser02@gmail.com",
    "C0018992",
    "eadam",
    "Female",
    "2001-02-21",
    "17035551213",
    "17035551213",
    "1",
    "1",
    "1",
    "Honolulu",
    "Hawaii",
    "96815",
    "Honolulu",
    "America/Adak",
  ],
  data: {
    integration_id: "Egon.Adam",
    family_name: "adam@#,%^&*-_;|test",
    middle_name: "test2",
    given_name: "egon",
    email: "",
    secondary_email: "testuser02@gmail.com",
    student_id: "C0018992",
    user_id: "eadam",
    gender: "Female",
    birth_dt: "2001-02-21",
    b_phone: "17035551213",
    m_phone: "17035551213",
    available_ind: "1",
    assign_student_role: "1",
    allow_login: "1",
    home_city: "Honolulu",
    home_state: "Hawaii",
    home_zip: "96815",
    home_county: "Honolulu",
    user_timezone: "America/Adak",
  },
  json: [
    "Egon.Adam",
    "adam@#,%^&*-_;|test",
    "test2",
    "egon",
    "",
    "testuser02@gmail.com",
    "C0018992",
    "eadam",
    "Female",
    "2001-02-21",
    "17035551213",
    "17035551213",
    "1",
    "1",
    "1",
    "Honolulu",
    "Hawaii",
    "96815",
    "Honolulu",
    "America/Adak",
  ],
  name: "users",
};

export const usersFileWithDuplicateIntegId = {
  index: 4,
  raw: [
    "Yolanda.Gold",
    "goldn",
    "test",
    "yolanda",
    "testuser02@gmail.com",
    "testuser02@gmail.com",
    "C0018992",
    "ygold",
    "Female",
    "2001-02-21",
    "17035551213",
    "17035551213",
    "1",
    "1",
    "1",
    "Honolulu",
    "Hawaii",
    "96815",
    "Honolulu",
    "America/Adak",
  ],
  data: {
    integration_id: "Yolanda.Gold",
    family_name: "gold",
    middle_name: "test",
    given_name: "yolanda",
    email: "testuser02@gmail.com",
    secondary_email: "testuser02@gmail.com",
    student_id: "C0018992",
    user_id: "ygold",
    gender: "Female",
    birth_dt: "2001-02-21",
    b_phone: "17035551213",
    m_phone: "17035551213",
    available_ind: "1",
    assign_student_role: "1",
    allow_login: "1",
    home_city: "Honolulu",
    home_state: "Hawaii",
    home_zip: "96815",
    home_county: "Honolulu",
    user_timezone: "America/Adak",
  },
  json: [
    "Yolanda.Gold",
    "gold",
    "test",
    "yolanda",
    "testuser02@gmail.com",
    "testuser02@gmail.com",
    "C0018992",
    "ygold",
    "Female",
    "2001-02-21",
    "17035551213",
    "17035551213",
    "1",
    "1",
    "1",
    "Honolulu",
    "Hawaii",
    "96815",
    "Honolulu",
    "America/Adak",
  ],
  name: "users",
};

export const enrollmentFileHeaderRow = {
  index: 1,
  raw: [
    "course_section_integration_id",
    "user_integration_id",
    "user_role",
    "available_ind",
    "credit_hours",
    "last_access_date",
    "authoritative_status",
  ],
  data: {
    course_section_integration_id: "course_section_integration_id",
    user_integration_id: "user_integration_id",
    user_role: "user_role",
    available_ind: "available_ind",
    credit_hours: "credit_hours",
    last_access_date: "last_access_date",
    authoritative_status: "authoritative_status",
  },
  json: [
    "course_section_integration_id",
    "user_integration_id",
    "user_role",
    "available_ind",
    "credit_hours",
    "last_access_date",
    "authoritative_status",
  ],
  name: "enrollment",
};

export const enrollmentFileMapsIntegID = {
  index: 2,
  raw: [
    "UNIV-SRF101-602-202002",
    "Yolanda.Gold",
    "Instructor",
    "1",
    "1.5",
    "2016-09-20 14:04:05",
    "1",
  ],
  data: {
    course_section_integration_id: "UNIV-SRF101-602-202002",
    user_integration_id: "Yolanda.Gold",
    user_role: "Instructor",
    available_ind: "1",
    credit_hours: "1.5",
    last_access_date: "2016-09-20 14:04:05",
    authoritative_status: "1",
  },
  json: [
    "UNIV-SRF101-602-202002",
    "Yolanda.Gold",
    "Instructor",
    "1",
    "1.5",
    "2016-09-20 14:04:05",
    "1",
  ],
  name: "enrollment",
};

export const enrollmentFileNoMatchIntegID = {
  index: 3,
  raw: [
    "UNIV-SRF101-602-202002",
    "Peter.Park",
    "Instructor",
    "1",
    "1.5",
    "2016-09-20 14:04:05",
    "1",
  ],
  data: {
    course_section_integration_id: "UNIV-SRF101-602-202002",
    user_integration_id: "Peter.Park",
    user_role: "Instructor",
    available_ind: "1",
    credit_hours: "1.5",
    last_access_date: "2016-09-20 14:04:05",
    authoritative_status: "1",
  },
  json: [
    "UNIV-SRF101-602-202002",
    "Peter.Park",
    "Instructor",
    "1",
    "1.5",
    "2016-09-20 14:04:05",
    "1",
  ],
  name: "enrollment",
};

export const relationshipsFileHeaderRow = {
  index: 1,
  raw: [
    "parent_integration_id",
    "parent_role",
    "child_id",
    "child_role",
    "term_id",
  ],
  data: {
    parent_integration_id: "parent_integration_id",
    parent_role: "parent_role",
    child_id: "child_id",
    child_role: "child_role",
    term_id: "term_id",
  },
  json: [
    "parent_integration_id",
    "parent_role",
    "child_id",
    "child_role",
    "term_id",
  ],
  name: "relationships",
};

export const relationshipsFileWithNoMatchIntegId = {
  index: 2,
  raw: ["Yolanda.Gold", "Primary Advisor", "Emma.Mack", "Student", "202002"],
  data: {
    parent_integration_id: "Yolanda.Gold",
    parent_role: "Primary Advisor",
    child_id: "Emma.Mack",
    child_role: "Student",
    term_id: "202002",
  },
  json: ["Yolanda.Gold", "Primary Advisor", "Emma.Mack", "Student", "202002"],
  name: "relationships",
};

export const relationshipsFileMapNoChildID = {
  index: 2,
  raw: ["Yolanda.Gold", "Primary Advisor", "adam.gold", "Student", "202002"],
  data: {
    parent_integration_id: "Yolanda.Gold",
    parent_role: "Primary Advisor",
    child_id: "adam.gold",
    child_role: "Student",
    term_id: "202002",
  },
  json: ["Yolanda.Gold", "Primary Advisor", "adam.gold", "Student", "202002"],
  name: "relationships",
};

export const sectionsFileHeaderRow = {
  index: 1,
  raw: [
    "integration_id",
    "course_section_name",
    "course_section_id",
    "start_dt",
    "end_dt",
    "term_id",
    "course_integration_id",
    "course_section_delivery",
    "maximum_enrollment_count",
    "credit_hours",
    "registration_call_number",
  ],
  data: {
    integration_id: "integration_id",
    course_section_name: "course_section_name",
    course_section_id: "course_section_id",
    start_dt: "start_dt",
    end_dt: "end_dt",
    term_id: "term_id",
    course_integration_id: "course_integration_id",
    course_section_delivery: "course_section_delivery",
    maximum_enrollment_count: "maximum_enrollment_count",
    credit_hours: "credit_hours",
    registration_call_number: "registration_call_number",
  },
  json: [
    "integration_id",
    "course_section_name",
    "course_section_id",
    "start_dt",
    "end_dt",
    "term_id",
    "course_integration_id",
    "course_section_delivery",
    "maximum_enrollment_count",
    "credit_hours",
    "registration_call_number",
  ],
  name: "sections",
};

export const sectionsFileNoAnonymizationRow = {
  index: 2,
  raw: [
    "UNIV-SRF101-602-202002",
    "Canvas Course",
    "UNIV-SRF101-602-202002",
    "2020-08-10",
    "2021-01-10",
    "202002",
    "SRF101",
    "03",
    "50",
    "3.5",
    "31533",
  ],
  data: {
    integration_id: "UNIV-SRF101-602-202002",
    course_section_name: "Canvas Course",
    course_section_id: "UNIV-SRF101-602-202002",
    start_dt: "2020-08-10",
    end_dt: "2021-01-10",
    term_id: "202002",
    course_integration_id: "SRF101",
    course_section_delivery: "03",
    maximum_enrollment_count: "50",
    credit_hours: "3.5",
    registration_call_number: "31533",
  },
  json: [
    "UNIV-SRF101-602-202002",
    "Canvas Course",
    "UNIV-SRF101-602-202002",
    "2020-08-10",
    "2021-01-10",
    "202002",
    "SRF101",
    "03",
    "50",
    "3.5",
    "31533",
  ],
  name: "sections",
};
